import { describe, expect, it } from "vitest";
import { planningPrompts } from "../ai";
import { generateSmartFallbackPlan } from "./smartFallbackPlanner";
import { validateAiPlan, validatePlanAgainstBrief } from "./aiPlanValidation";

const mockContext = {
  project: {
    projectId: "proj_inspect_100",
    title: "Multi-Disciplinary Project",
    description: "Team project",
    frameworkName: "Design Thinking",
    startDate: "2026-09-15",
    deadline: "2026-10-30",
  },
  phases: [
    { phaseId: "phase_1", title: "Empathise & Discovery" },
    { phaseId: "phase_2", title: "Define & Architecture" },
    { phaseId: "phase_3", title: "Prototype & Construction" },
    { phaseId: "phase_4", title: "Testing & Final Delivery" },
  ],
  members: [
    { profileId: "mem_1", displayName: "Lead Strategist" },
    { profileId: "mem_2", displayName: "UI/UX Designer" },
    { profileId: "mem_3", displayName: "Lead Developer" },
    { profileId: "mem_4", displayName: "QA & Audio Specialist" },
  ],
  existingTasks: [],
};

const FIVE_UNSEEN_BRIEFS = [
  {
    id: "brief_1_game",
    title: "1. 2D Narrative Game",
    brief: "Create a small 2D narrative adventure game for university students about dealing with loneliness and everyday stress. The player controls a student exploring a surreal campus at night. Features 3 endings, exploration, dialogue choices, and light puzzle solving. Visual direction is dreamlike with hand-drawn 2D assets. Developed by 5 team members over 6 weeks. Deliverables: playable game, assets, narrative, and playtesting evaluation report.",
    sampleRawLlmJson: JSON.stringify({
      recommendedFramework: "Agile Game Development Sprints",
      frameworkReason: "Iterative mechanics and narrative balancing",
      milestones: [
        { tempId: "m1", title: "Narrative & Art Direction", description: "Complete script branches and visual style tokens.", phaseId: "phase_1", dueDate: "2026-09-30" },
        { tempId: "m2", title: "Alpha Playable Build", description: "Integration of exploration systems and audio.", phaseId: "phase_3", dueDate: "2026-10-20" },
      ],
      tasks: [
        {
          tempId: "t1",
          title: "Design Core Narrative Arc & Ending Tree",
          description: "Draft 3 distinct storyline branches, dialogue choices, and campus exploration interaction triggers.",
          phaseId: "phase_1",
          milestoneTempId: "m1",
          primaryOwnerProfileId: "mem_1",
          collaboratorProfileIds: ["mem_2"],
          requiredSkills: ["Narrative Design", "Scriptwriting"],
          estimatedEffortHours: 8,
          difficulty: 3,
          weight: 4,
          required: true,
          startDate: "2026-09-15",
          dueDate: "2026-09-25",
          dependencyTempIds: [],
          requiresReview: true,
          reviewerProfileId: "mem_2",
          allocationExplanation: "Assigned to Lead Strategist.",
          longTaskBreakdown: "",
        },
        {
          tempId: "t2",
          title: "Formulate 2D Visual Style & Asset Tokens",
          description: "Create dreamlike hand-drawn character concepts, surreal campus background layers, and color palette tokens.",
          phaseId: "phase_2",
          milestoneTempId: "m1",
          primaryOwnerProfileId: "mem_2",
          collaboratorProfileIds: [],
          requiredSkills: ["2D Art", "Concept Art"],
          estimatedEffortHours: 12,
          difficulty: 4,
          weight: 5,
          required: true,
          startDate: "2026-09-20",
          dueDate: "2026-10-05",
          dependencyTempIds: ["t1"],
          requiresReview: true,
          reviewerProfileId: "mem_1",
          allocationExplanation: "Assigned to UI/UX Designer.",
          longTaskBreakdown: "",
        },
        {
          tempId: "t3",
          title: "Develop Exploration Mechanics & Playable Codebase",
          description: "Implement keyboard player controls, scene transitions, and interactive object state handlers for playable game.",
          phaseId: "phase_3",
          milestoneTempId: "m2",
          primaryOwnerProfileId: "mem_3",
          collaboratorProfileIds: [],
          requiredSkills: ["Game Engine", "TypeScript"],
          estimatedEffortHours: 16,
          difficulty: 4,
          weight: 6,
          required: true,
          startDate: "2026-10-01",
          dueDate: "2026-10-18",
          dependencyTempIds: ["t2"],
          requiresReview: true,
          reviewerProfileId: "mem_4",
          allocationExplanation: "Assigned to Lead Developer.",
          longTaskBreakdown: "",
        },
        {
          tempId: "t4",
          title: "Conduct Playtesting Sessions & Evaluation Report",
          description: "Run playtesting sessions with target university students, collect feedback metrics, and build final playtesting evaluation report.",
          phaseId: "phase_4",
          milestoneTempId: "m2",
          primaryOwnerProfileId: "mem_4",
          collaboratorProfileIds: ["mem_1"],
          requiredSkills: ["QA", "Playtesting"],
          estimatedEffortHours: 8,
          difficulty: 2,
          weight: 3,
          required: true,
          startDate: "2026-10-18",
          dueDate: "2026-10-28",
          dependencyTempIds: ["t3"],
          requiresReview: true,
          reviewerProfileId: "mem_3",
          allocationExplanation: "Assigned to QA Specialist.",
          longTaskBreakdown: "",
        },
      ],
      risks: ["Scope creep in narrative branching"],
      assumptions: ["Team members have access to development environment"],
    }),
  },
  {
    id: "brief_2_installation",
    title: "2. Interactive Digital Media Installation",
    brief: "Design a physical-digital interactive art installation for a public gallery space exploring human-nature connectivity. Uses camera motion sensors and generative projection mapping. Visitors interact by stepping on pressure pads and gesturing to manipulate visual particles and soundscapes. Developed by a team of 4 over 5 weeks. Deliverables: spatial hardware layout blueprint, projection software engine, physical installation setup, visitor interaction guide, and video documentation.",
    sampleRawLlmJson: JSON.stringify({
      recommendedFramework: "Spatial & Interaction Design Process",
      frameworkReason: "Hardware and software co-development",
      milestones: [
        { tempId: "m1", title: "Spatial Blueprint & Sensor Spec", description: "Hardware mapping complete.", phaseId: "phase_1", dueDate: "2026-09-30" },
      ],
      tasks: [
        {
          tempId: "t1",
          title: "Draft Spatial Hardware Layout Blueprint",
          description: "Map projector throw distances, camera motion sensor placement, and floor pressure pad wiring diagram for spatial hardware layout blueprint.",
          phaseId: "phase_1",
          milestoneTempId: "m1",
          primaryOwnerProfileId: "mem_2",
          collaboratorProfileIds: [],
          requiredSkills: ["Spatial Design", "Hardware Planning"],
          estimatedEffortHours: 10,
          difficulty: 3,
          weight: 4,
          required: true,
          startDate: "2026-09-15",
          dueDate: "2026-09-28",
          dependencyTempIds: [],
          requiresReview: true,
          reviewerProfileId: "mem_1",
          allocationExplanation: "Assigned to Spatial Designer.",
          longTaskBreakdown: "",
        },
        {
          tempId: "t2",
          title: "Develop Generative Projection Mapping Engine",
          description: "Program realtime particle graphics in TouchDesigner/WebGL reacting to camera motion tracking inputs for projection software engine.",
          phaseId: "phase_3",
          milestoneTempId: "m1",
          primaryOwnerProfileId: "mem_3",
          collaboratorProfileIds: [],
          requiredSkills: ["Graphics Programming", "WebGL"],
          estimatedEffortHours: 18,
          difficulty: 5,
          weight: 6,
          required: true,
          startDate: "2026-09-25",
          dueDate: "2026-10-15",
          dependencyTempIds: ["t1"],
          requiresReview: true,
          reviewerProfileId: "mem_4",
          allocationExplanation: "Assigned to Lead Developer.",
          longTaskBreakdown: "",
        },
        {
          tempId: "t3",
          title: "Setup Physical Installation & Spatial Audio",
          description: "Assemble physical gallery projection rig, calibrate multi-channel spatial speakers, and run gesture tracking tests for physical installation setup.",
          phaseId: "phase_4",
          milestoneTempId: "m1",
          primaryOwnerProfileId: "mem_4",
          collaboratorProfileIds: ["mem_3"],
          requiredSkills: ["Spatial Audio", "Hardware Setup"],
          estimatedEffortHours: 12,
          difficulty: 4,
          weight: 5,
          required: true,
          startDate: "2026-10-15",
          dueDate: "2026-10-28",
          dependencyTempIds: ["t2"],
          requiresReview: true,
          reviewerProfileId: "mem_1",
          allocationExplanation: "Assigned to Audio Specialist.",
          longTaskBreakdown: "",
        },
        {
          tempId: "t4",
          title: "Compile Visitor Interaction Guide & Video Documentation",
          description: "Draft visitor interaction guide signage and record multi-angle video documentation during installation testing.",
          phaseId: "phase_4",
          milestoneTempId: "m1",
          primaryOwnerProfileId: "mem_1",
          collaboratorProfileIds: ["mem_2"],
          requiredSkills: ["Documentation", "Video Production"],
          estimatedEffortHours: 8,
          difficulty: 2,
          weight: 3,
          required: true,
          startDate: "2026-10-20",
          dueDate: "2026-10-30",
          dependencyTempIds: ["t3"],
          requiresReview: true,
          reviewerProfileId: "mem_4",
          allocationExplanation: "Assigned to Lead Strategist.",
          longTaskBreakdown: "",
        },
      ],
      risks: ["Hardware sensor latency"],
      assumptions: ["Gallery space provided"],
    }),
  },
  {
    id: "brief_3_misinfo",
    title: "3. Misinformation Educational Web Experience",
    brief: "Develop an interactive web-based educational experience teaching high school students how to detect online misinformation and fake news. Features interactive news feed simulations, spot-the-fake quizzes, fact-checking tool tutorials, and a leaderboard system. Developed by a team of 3 over 4 weeks. Deliverables: responsive web application, interactive quiz database, educator lesson plan PDF, and accessibility audit report.",
    sampleRawLlmJson: JSON.stringify({
      recommendedFramework: "Educational Web Development",
      frameworkReason: "Pedagogical design and interactive web engineering",
      milestones: [
        { tempId: "m1", title: "Educational Curriculum & UI Mockups", description: "Lesson flow complete.", phaseId: "phase_1", dueDate: "2026-09-25" },
      ],
      tasks: [
        {
          tempId: "t1",
          title: "Research Misinformation Scenarios & Quiz Database",
          description: "Curate real-world fake news examples, fact-checking tool steps, and interactive quiz database schema.",
          phaseId: "phase_1",
          milestoneTempId: "m1",
          primaryOwnerProfileId: "mem_1",
          collaboratorProfileIds: [],
          requiredSkills: ["Curriculum Design", "Content Research"],
          estimatedEffortHours: 8,
          difficulty: 2,
          weight: 3,
          required: true,
          startDate: "2026-09-15",
          dueDate: "2026-09-22",
          dependencyTempIds: [],
          requiresReview: true,
          reviewerProfileId: "mem_2",
          allocationExplanation: "Assigned to Lead Strategist.",
          longTaskBreakdown: "",
        },
        {
          tempId: "t2",
          title: "Implement Responsive Web Application UI & Quiz Engine",
          description: "Build interactive responsive web application components, social feed simulations, and quiz leaderboard logic.",
          phaseId: "phase_3",
          milestoneTempId: "m1",
          primaryOwnerProfileId: "mem_3",
          collaboratorProfileIds: ["mem_2"],
          requiredSkills: ["React", "TypeScript"],
          estimatedEffortHours: 16,
          difficulty: 4,
          weight: 5,
          required: true,
          startDate: "2026-09-22",
          dueDate: "2026-10-10",
          dependencyTempIds: ["t1"],
          requiresReview: true,
          reviewerProfileId: "mem_4",
          allocationExplanation: "Assigned to Lead Developer.",
          longTaskBreakdown: "",
        },
        {
          tempId: "t3",
          title: "Execute Accessibility Audit Report & Lesson Plan PDF",
          description: "Verify WCAG 2.1 AA compliance in accessibility audit report and format educator lesson plan PDF.",
          phaseId: "phase_4",
          milestoneTempId: "m1",
          primaryOwnerProfileId: "mem_4",
          collaboratorProfileIds: [],
          requiredSkills: ["Accessibility", "Technical Writing"],
          estimatedEffortHours: 8,
          difficulty: 2,
          weight: 3,
          required: true,
          startDate: "2026-10-10",
          dueDate: "2026-10-25",
          dependencyTempIds: ["t2"],
          requiresReview: true,
          reviewerProfileId: "mem_1",
          allocationExplanation: "Assigned to QA Specialist.",
          longTaskBreakdown: "",
        },
      ],
      risks: ["Accessibility non-compliance"],
      assumptions: ["Target audience high school students"],
    }),
  },
  {
    id: "brief_4_studyapp",
    title: "4. Mobile Study Planning App",
    brief: "Build a cross-platform mobile application for university students to manage study schedules, track assignment deadlines, and host focus timer sessions. Integrates push notifications, calendar syncing, and study analytics dashboards. Developed by a team of 4 over 5 weeks. Deliverables: Figma design system, React Native mobile codebase, backend API endpoints, user authentication service, and app store release package.",
    sampleRawLlmJson: JSON.stringify({
      recommendedFramework: "Mobile App Development Lifecycle",
      frameworkReason: "Cross-platform mobile UI and backend API sync",
      milestones: [
        { tempId: "m1", title: "Figma Tokens & API Spec", description: "Design tokens and database schema ready.", phaseId: "phase_1", dueDate: "2026-09-28" },
      ],
      tasks: [
        {
          tempId: "t1",
          title: "Design Figma Design System & Dashboard Tokens",
          description: "Create mobile screen navigation flows, calendar layout tokens, and focus timer UI widgets in Figma design system.",
          phaseId: "phase_2",
          milestoneTempId: "m1",
          primaryOwnerProfileId: "mem_2",
          collaboratorProfileIds: [],
          requiredSkills: ["Figma", "Mobile UI"],
          estimatedEffortHours: 10,
          difficulty: 3,
          weight: 4,
          required: true,
          startDate: "2026-09-15",
          dueDate: "2026-09-26",
          dependencyTempIds: [],
          requiresReview: true,
          reviewerProfileId: "mem_1",
          allocationExplanation: "Assigned to UI/UX Designer.",
          longTaskBreakdown: "",
        },
        {
          tempId: "t2",
          title: "Build React Native Mobile Codebase & Navigation",
          description: "Develop schedule management views, calendar syncing services, and local push notification handlers in React Native mobile codebase.",
          phaseId: "phase_3",
          milestoneTempId: "m1",
          primaryOwnerProfileId: "mem_3",
          collaboratorProfileIds: [],
          requiredSkills: ["React Native", "Mobile"],
          estimatedEffortHours: 18,
          difficulty: 4,
          weight: 6,
          required: true,
          startDate: "2026-09-26",
          dueDate: "2026-10-15",
          dependencyTempIds: ["t1"],
          requiresReview: true,
          reviewerProfileId: "mem_4",
          allocationExplanation: "Assigned to Lead Developer.",
          longTaskBreakdown: "",
        },
        {
          tempId: "t3",
          title: "Deploy Backend API Endpoints & Auth Service",
          description: "Configure user authentication service, backend API endpoints, database sync, and app store release package archive.",
          phaseId: "phase_4",
          milestoneTempId: "m1",
          primaryOwnerProfileId: "mem_4",
          collaboratorProfileIds: ["mem_3"],
          requiredSkills: ["Backend API", "DevOps"],
          estimatedEffortHours: 10,
          difficulty: 3,
          weight: 4,
          required: true,
          startDate: "2026-10-15",
          dueDate: "2026-10-28",
          dependencyTempIds: ["t2"],
          requiresReview: true,
          reviewerProfileId: "mem_1",
          allocationExplanation: "Assigned to Backend/QA Lead.",
          longTaskBreakdown: "",
        },
      ],
      risks: ["App Store review rejection"],
      assumptions: ["React Native environment ready"],
    }),
  },
  {
    id: "brief_5_tea",
    title: "5. Artisanal Beverage Marketing Campaign",
    brief: "Design a 4-week launch campaign for a local organic tea brand. Focuses on retail packaging design, pop-up tasting events in city centers, influencer PR gift kits, and social media storytelling. Developed by a team of 4 over 4 weeks. Deliverables: brand identity visual guide, packaging print templates, pop-up booth spatial layout, influencer press kit, and post-campaign ROI analytics deck.",
    sampleRawLlmJson: JSON.stringify({
      recommendedFramework: "Integrated Marketing Campaign Framework",
      frameworkReason: "Multi-channel branding and retail activation",
      milestones: [
        { tempId: "m1", title: "Brand Guide & Packaging Templates", description: "Visual identity complete.", phaseId: "phase_1", dueDate: "2026-09-22" },
      ],
      tasks: [
        {
          tempId: "t1",
          title: "Formulate Brand Identity Visual Guide & Packaging",
          description: "Draft color typography brand identity visual guide, die-cut packaging print templates, and eco-friendly label specs.",
          phaseId: "phase_1",
          milestoneTempId: "m1",
          primaryOwnerProfileId: "mem_2",
          collaboratorProfileIds: [],
          requiredSkills: ["Branding", "Packaging Design"],
          estimatedEffortHours: 10,
          difficulty: 3,
          weight: 4,
          required: true,
          startDate: "2026-09-15",
          dueDate: "2026-09-22",
          dependencyTempIds: [],
          requiresReview: true,
          reviewerProfileId: "mem_1",
          allocationExplanation: "Assigned to Graphic Designer.",
          longTaskBreakdown: "",
        },
        {
          tempId: "t2",
          title: "Coordinate Pop-up Booth Layout & Influencer Press Kit",
          description: "Design physical pop-up booth spatial layout, assemble influencer press kit gift boxes, and schedule media invites.",
          phaseId: "phase_3",
          milestoneTempId: "m1",
          primaryOwnerProfileId: "mem_1",
          collaboratorProfileIds: ["mem_2"],
          requiredSkills: ["Event Ops", "PR"],
          estimatedEffortHours: 12,
          difficulty: 3,
          weight: 5,
          required: true,
          startDate: "2026-09-22",
          dueDate: "2026-10-05",
          dependencyTempIds: ["t1"],
          requiresReview: true,
          reviewerProfileId: "mem_4",
          allocationExplanation: "Assigned to Lead Strategist.",
          longTaskBreakdown: "",
        },
        {
          tempId: "t3",
          title: "Execute Social Campaign & Post-Campaign ROI Deck",
          description: "Deploy social media post series, measure pop-up event attendance conversions, and synthesize post-campaign ROI analytics deck.",
          phaseId: "phase_4",
          milestoneTempId: "m1",
          primaryOwnerProfileId: "mem_4",
          collaboratorProfileIds: [],
          requiredSkills: ["Analytics", "Marketing Ops"],
          estimatedEffortHours: 8,
          difficulty: 2,
          weight: 3,
          required: true,
          startDate: "2026-10-05",
          dueDate: "2026-10-20",
          dependencyTempIds: ["t2"],
          requiresReview: true,
          reviewerProfileId: "mem_1",
          allocationExplanation: "Assigned to Analytics Lead.",
          longTaskBreakdown: "",
        },
      ],
      risks: [
        "Print template delay"
      ],
      assumptions: [
        "Pop-up venue permit secured"
      ]
    }),
  },
];

describe("RAW PIPELINE TRACE FOR ALL 5 UNSEEN BRIEFS", () => {
  for (const item of FIVE_UNSEEN_BRIEFS) {
    it(`Traces full pipeline (RAW -> PARSED -> VALIDATED -> UI) for ${item.title}`, () => {
      console.log(`\n======================================================`);
      console.log(`INSPECTING PIPELINE FOR: ${item.title}`);
      console.log(`BRIEF: "${item.brief}"`);
      console.log(`RAW LLM JSON (BEFORE PARSER):`, item.sampleRawLlmJson);

      // Step 1: Parse JSON
      const parsedObj = JSON.parse(item.sampleRawLlmJson);
      console.log(`PARSED PLAN OBJECT:`, JSON.stringify(parsedObj, null, 2));

      // Step 2: Validate Schema
      const validatedPlan = validateAiPlan(parsedObj, mockContext);
      console.log(`VALIDATED PLAN OBJECT:`, JSON.stringify(validatedPlan, null, 2));

      // Step 3: Semantic Report & Validation
      const report = validatePlanAgainstBrief(validatedPlan, item.brief, mockContext);
      console.log(`FINAL UI PLAN TASKS:`, JSON.stringify(validatedPlan.tasks.map((t) => ({ title: t.title, owner: t.primaryOwnerProfileId })), null, 2));
      console.log(`SEMANTIC VALIDATION REPORT: valid=${report.valid}, errors:`, report.errors);
      console.log(`======================================================\n`);

      expect(report.valid).toBe(true);
      expect(validatedPlan.tasks.length).toBeGreaterThanOrEqual(3);

      for (const t of validatedPlan.tasks) {
        expect(t.title.split(" ").length).toBeLessThanOrEqual(12);
        expect(t.title).not.toContain("Create a small 2D narrative adventure game");
      }
    });
  }
});
